[[redirects]]
from = "https://fastidious-souffle-2fd946.netlify.app/api/v1/*"
to = "http://13.125.167.122:8081/:splat"
status = 200

[[redirects]]
from = "https://fastidious-souffle-2fd946.netlify.app/api/v1/*"
to = "http://3.38.9.104:8080/:splat"
status = 200
